# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysqlcontainer
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: userativo
      MYSQL_PASSWORD: passativo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ativo_bff
  #jaeger:
  #  image: jaegertracing/all-in-one:1.29
  #  container_name: jaeger
  #  ports:
  #    - 5775:5775/udp
  #    - 6831:6831/udp
  #    - 6832:6832/udp
  #    - 5778:5778
  #    - 16686:16686
  #    - 14250:1425
  #    - 14268:14268
  #    - 14269:14269
  #    - 9411:9411