# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysqlcontainer
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: userativo
      MYSQL_PASSWORD: passativo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ativo_bff
  #jaeger:
  #  image: jaegertracing/all-in-one:1.29
  #  container_name: jaeger
  #  ports:
  #    - 5775:5775/udp
  #    - 6831:6831/udp
  #    - 6832:6832/udp
  #    - 5778:5778
  #    - 16686:16686
  #    - 14250:1425
  #    - 14268:14268
  #    - 14269:14269
  #    - 9411:9411
  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana_container
    ports:
      - 3000:3000
  microsservico_app:
    container_name: app_ativobff_container
    ports:
      - 8080:8080
    depends_on:
      - grafana
      - db
    build: docker_ms
    command: ["-c", "/user/server/wait-for-mysql.sh db:3306 && java -jar /usr/server/investpess-bffweb-ativo.jar"]
    entrypoint: ["/bin/sh"]
